### ISSUE TITLE
React-native fails to run

### ISSUE THREAD

**Issue by acg9** [nodejs/node-chakracore#107]
- **Version**: 6.0.0
- **Platform**: 64-bit Windows redstone

I'm trying to run the react-native getting started [example ](https://facebook.github.io/react-native/docs/getting-started.html#testing-your-react-native-installation)in windows for android but after running

```
react-native run-android
```

I get the following error:

```
TypeError: Object doesn't support property or method 'isNative'
   at CallSiteToString (X:\code\react_native\AwesomeProject\node_modules\source-map-support\source-map-support.js:195:3)
   at Anonymous function (X:\code\react_native\AwesomeProject\node_modules\source-map-support\source-map-support.js:304:5)
   at Array.prototype.map (native code)
   at prepareStackTrace (X:\code\react_native\AwesomeProject\node_modules\source-map-support\source-map-support.js:303:3)
   at stackGetter (Unknown script code:208:9)
   at socketErrorListener (_http_client.js:303:3)
   at emitOne (events.js:96:5)
   at emit (events.js:188:7)
   at emitErrorNT (net.js:1265:3)
   at _combinedTickCallback (internal/process/next_tick.js:74:11)
```

**Comment by kunalspathak** [comment]
Thanks @Iscgx for reporting. We will take a look into it and update what is going on.
