### ISSUE TITLE
eslint not working due to "object shorthand" syntax

### ISSUE THREAD

**Issue by alexlamsl** [nodejs/node-chakracore#118]
For now I have to manually edit [this line](https://github.com/eslint/eslint/blob/v3.5.0/lib/eslint.js#L62) for `eslint` to work on `node-chakracore`, otherwise I get the following error:

```
'comment' is undefined
ReferenceError: 'comment' is undefined
   at Anonymous function (eslint\lib\eslint.js:60:9)
   at Array.prototype.forEach (native code)
   at parseBooleanConfig (eslint\lib\eslint.js:48:5)
   at Anonymous function (eslint\lib\eslint.js:332:25)
   at Array.prototype.forEach (native code)
   at modifyConfigsFromComments (eslint\lib\eslint.js:316:5)
   at api.verify (eslint\lib\eslint.js:806:17)
   at processText (eslint\lib\cli-engine.js:262:13)
   at processFile (eslint\lib\cli-engine.js:297:9)
   at executeOnFile (eslint\lib\cli-engine.js:667:13)
```

**Comment by kunalspathak** [comment]
Thanks @alexlamsl for reporting. Could you clarify the exact repro steps / command you are using?

**Comment by alexlamsl** [comment]
What I did (on Windows Server 2012 R2)

```
> git clone https://github.com/kangax/html-minifier.git
> cd html-minifier
> npm install --no-optional
> npm run test
...
Running "eslint:grunt" (eslint) task


Running "eslint:src" (eslint) task
Warning: 'comment' is undefined Use --force to continue.

Aborted due to warnings.

npm ERR! Windows_NT 6.3.9600
...
```

More specifically

```
> node_modules\.bin\eslint src\htmlparser.js
'comment' is undefined
ReferenceError: 'comment' is undefined
   at Anonymous function (eslint\lib\eslint.js:60:9)
   at Array.prototype.forEach (native code)
   at parseBooleanConfig (eslint\lib\eslint.js:48:5)
   at Anonymous function (eslint\lib\eslint.js:332:25)
   at Array.prototype.forEach (native code)
   at modifyConfigsFromComments (eslint\lib\eslint.js:316:5)
   at api.verify (eslint\lib\eslint.js:806:17)
   at processText (eslint\lib\cli-engine.js:262:13)
   at processFile (eslint\lib\cli-engine.js:297:9)
   at executeOnFile (eslint\lib\cli-engine.js:667:13)

```

**Comment by kunalspathak** [comment]
Have you tried one of the below [nightly official builds](https://nodejs.org/download/nightly/) of node.js and see if it repros?

![image](https://cloud.githubusercontent.com/assets/12488060/18594529/6ddfaa40-7bf5-11e6-89e5-3354cdbd5916.png)

**Comment by alexlamsl** [comment]
So it doesn't like `comment` in here:

```
items[name] = {
  value: (value === "true"),
  comment
};
```

Two things I've tried so far that worked. One is to simply use `comment:comment` which is expected. Another more surprising way is to add `console.log(comment)` immediately before `items[name]`.

**Comment by alexlamsl** [comment]
@kunalspathak no I haven't tried nightly builds before. I'll give it a go now and report back...

**Comment by alexlamsl** [comment]
Works fine with `v7.0.0-nightly20160915ea2a309e3b`

**Comment by kunalspathak** [comment]
Thanks for confirming @alexlamsl . Seems like some bug in parser. I will take a look.

**Comment by alexlamsl** [comment]
I have a slightly reduced test case with just `eslint` on (Node.js) command line:

```
> require('eslint/lib/eslint').verify('/* global a */',{},'')
ReferenceError: 'comment' is undefined
   at Anonymous function (eslint\lib\eslint.js:60:9)
   at Array.prototype.forEach (native code)
   at parseBooleanConfig (eslint\lib\eslint.js:48:5)
   at Anonymous function (eslint\lib\eslint.js:332:25)
   at Array.prototype.forEach (native code)
   at modifyConfigsFromComments (eslint\lib\eslint.js:316:5)
   at api.verify (eslint\lib\eslint.js:806:17)
   at Global code (repl:1:1)
   at Anonymous function (vm.js:22:7)
   at sigintHandlersWrap (vm.js:96:5)
```

**Comment by kunalspathak** [comment]
Great! I appreciate your efforts in reducing the scenario. I will look into it.

**Comment by alexlamsl** [comment]
@kunalspathak it's me again 😅 

This time I have a completely standalone case which is very curious:

``` js
function f(a) {
  [0].forEach(function() {
    return {a};
  });
}
// ... 3960 bytes of comment in between ...
f();
```

If you run the file above:

```
>node test.js
ReferenceError: 'a' is undefined
   at Anonymous function (test.js:3:5)
   at Array.prototype.forEach (native code)
   at f (test.js:2:3)
   at Anonymous function (test.js:46:1)
   at Module.prototype._compile (module.js:560:3)
   at Module._extensions[.js] (module.js:569:3)
   at Module.prototype.load (module.js:477:3)
   at tryModuleLoad (module.js:436:5)
   at Module._load (module.js:428:3)
   at Module.runMain (module.js:594:3)
```

Removing a single byte from the comment section and the error would go away.

**Comment by kunalspathak** [comment]
Thanks @alexlamsl  once again. 😄 

I haven't got chance to investigate this issue, but the repros you are providing are definitely helpful in our investigation. I will get back to you once I find the problem

**Comment by digitalinfinity** [comment]
Thanks @alexlamsl for the short repro- it was a tremendous help. I spent some time debugging this- I've opened Microsoft/ChakraCore#1705 to track this.
