### ISSUE TITLE
Error: Internal Error on https.request().setTimeout()

### ISSUE THREAD

**Issue by alexlamsl** [nodejs/node-chakracore#133]
Version: v7.0.0-pre9
Platform: Windows 10
Subsystem: events?

This isn't always reproducible, but with a script running a bunch of `https` client requests occasionally one would fail with this splat:

```
Error: Internal error
   at _addListener (events.js:256:7)
   at addListener (events.js:275:3)
   at once (events.js:301:3)
   at ClientRequest.prototype.setTimeout (_http_client.js:635:3)
```

The code that triggers this is roughly (throws on final line):

``` js
var https = require('https');
var parse = require('url').parse;
var request = https.request(parse('https://example.com/'), function() {...});
request.on('error', function() {...});
request.setTimeout(30000, function() {
  request.abort();
});
```

**Comment by kunalspathak** [comment]
Thanks @alexlamsl . We will look into it.

**Comment by alexlamsl** [comment]
Not reproducible as of `v10.1.0`
