### ISSUE TITLE
ES6 Modules Support

### ISSUE THREAD

**Issue by d3x0r** [nodejs/node-chakracore#15]
Sample Code...

```
//------ main.js ------
import * as lib from 'lib';

console.log(lib.square(11)); // 121
console.log(lib.diag(4, 3)); // 5
```

```
//------ lib.js ------
export const sqrt = Math.sqrt;
export function square(x) {
    return x * x;
}
export function diag(x, y) {
    return sqrt(square(x) + square(y));
}

//------ main.js ------
import { square, diag } from 'lib';
console.log(square(11)); // 121
console.log(diag(4, 3)); // 5
```

Output

```
M:\javascript\module-test>"H:\dev2\nodejs (chakracore)\node" main.js
SyntaxError: Syntax error
   at tryWrapper (module.js:31:5)
   at Module.prototype._compile (module.js:397:3)
   at Module._extensions[.js] (module.js:432:3)
   at Module.prototype.load (module.js:367:3)
   at Module._load (module.js:324:5)
   at Module.runMain (module.js:457:3)
   at startup (node.js:139:11)
   at Anonymous function (node.js:1001:3)
```

Not very informative error; nodeJS with V8 Usually outputs the source line in question... as in

NodeJS (V8)

```
M:\javascript\module-test>h:\dev2\nodejs\node main.js
M:\javascript\module-test\main.js:2
import * as lib from 'lib';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:1003:3
```

**Comment by kunalspathak** [comment]
@d3x0r , Thanks for reporting. There are differences in the Syntax error messages and chakracore doesn't show the source line in question. Feel free to open issue at Microsoft/ChakraCore repo.

If you see https://github.com/Microsoft/node/commit/0faa5df2b9ac70157208efa90cbcde2526221b37 , we are aware of error differences and had to add if-else in unit test to differentiate between v8. and chakra.

**Comment by kunalspathak** [comment]
Thanks @d3x0r . I will close this issue as you have an open issue in chakracore.
