### ISSUE TITLE
node-bunyan unit test failure

### ISSUE THREAD

**Issue by kunalspathak** [nodejs/node-chakracore#176]
* **Version**: v8.0.0-pre
* **Platform**: 14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**: chakrashim

```bash
kunalspathak@kunalspathak-Virtual-Machine:~/git/node-bunyan$ node ./node_modules/.bin/nodeunit test/src.test.js

src.test.js
✖ src

TypeError: Unable to get property 'getFileName' of undefined or null reference
   at Error.prepareStackTrace (/home/kunalspathak/git/node-bunyan/lib/bunyan.js:195:9)
   at stackGetter (chakra_shim.js:245:9)
   at getCaller3Info (/home/kunalspathak/git/node-bunyan/lib/bunyan.js:202:5)


FAILURES: 1/1 assertions failed (65ms)
kunalspathak@kunalspathak-Virtual-Machine:~/git/node-bunyan$

```

**Comment by kfarnung** [comment]
@boingoing Can you take a look at this as part of the CITGM work?
