### ISSUE TITLE
test: UT failure - parallel/test-vm-sigint

### ISSUE THREAD

**Issue by kfarnung** [nodejs/node-chakracore#257]
This only repros on Linux since the test is skipped on Windows.

[Example CI run](https://ci.nodejs.org/job/chakracore-test-linux/81/nodes=ubuntu1604-64/tapResults/)

```
FATAL ERROR: v8::ToLocalChecked: Empty MaybeLocal.
Error
   at nextTick (internal/process/next_tick.js:247:5)
   at target._send (internal/child_process.js:657:9)
   at target.send (internal/child_process.js:549:7)
   at Global code (evalmachine.<anonymous>:1:1)
   at Script.prototype.runInContext (vm.js:53:5)
   at runInContext (vm.js:107:3)
   at Anonymous function (/home/iojs/build/workspace/chakracore-test-linux/nodes/ubuntu1604-64/test/parallel/test-vm-sigint.js:29:25)
   at _tryBlock (assert.js:518:5)
   at _throws (assert.js:539:3)
   at throws (assert.js:569:3)
AssertionError [ERR_ASSERTION]: 'SIGABRT' === null
   at Anonymous function (/home/iojs/build/workspace/chakracore-test-linux/nodes/ubuntu1604-64/test/parallel/test-vm-sigint.js:46:7)
   at Anonymous function (/home/iojs/build/workspace/chakracore-test-linux/nodes/ubuntu1604-64/test/common/index.js:518:5)
   at emitTwo (events.js:125:5)
   at emit (events.js:213:7)
   at maybeClose (internal/child_process.js:887:5)
   at _handle.onexit (internal/child_process.js:208:5)
```

**Comment by kunalspathak** [comment]
Below test cases are failing as well and root case seems to be same. The script engine is in exception state and host tries to allocate string which returns error.

* parallel/test-vm-sigint 
* parallel/test-vm-sigint-existing-handler 
* parallel/test-repl-init

```cmd
 FATAL ERROR: v8::ToLocalChecked: Empty MaybeLocal.
    Important: While trying to check Javascript exception, JsHasException has also failed.
    FATAL ERROR: v8::ToLocalChecked: Empty MaybeLocal.
    Important: While trying to check Javascript exception, JsHasException has also failed.
    AssertionError [ERR_ASSERTION]: 'SIGABRT' === null
       at Anonymous function (/home/iojs/build/workspace/chakracore-test-linux/nodes/ubuntu1604-64/test/parallel/test-vm-sigint-existing-handler.js:84:5)
       at Anonymous function (/home/iojs/build/workspace/chakracore-test-linux/nodes/ubuntu1604-64/test/common/index.js:518:5)
       at emitTwo (events.js:125:5)
       at emit (events.js:213:7)
       at maybeClose (internal/child_process.js:887:5)
       at _handle.onexit (internal/child_process.js:208:5)
  ...
```

**Comment by kfarnung** [comment]
As @MSLaguana pointed out, these tests can leave zombie node processes around that ultimately fail the CI run. We may want to consider just skipping them completely.
