### ISSUE TITLE
Investigate new inspector test failure

### ISSUE THREAD

**Issue by kfarnung** [nodejs/node-chakracore#292]
After the latest merge there's a new failure in `test-inspector-break-when-eval`:
```
=== release test-inspector-break-when-eval ===
Path: inspector/test-inspector-break-when-eval
[err] Debugger listening on ws://127.0.0.1:9229/0d830af1-98c3-4813-97cb-35a62fbb10dc
[err] For help see https://nodejs.org/en/docs/inspector
[err] 
[test] Setting up a debugger
[out] Ready!
[out] 
[test] Breaking in the code
AssertionError [ERR_ASSERTION]: {"error":{"code":-32000,"message":"Failed to evaluate expression"},"id":100006} (replying to undefined)
   at TestSession.prototype.processMessage_ (E:\GitHub\node-chakracore3\test\inspector\inspector-helper.js:197:5)
   at parseWSFrame (E:\GitHub\node-chakracore3\test\inspector\inspector-helper.js:80:3)
   at Anonymous function (E:\GitHub\node-chakracore3\test\inspector\inspector-helper.js:155:7)
   at emitOne (events.js:115:5)
   at emit (events.js:210:7)
   at addChunk (_stream_readable.js:250:5)
   at readableAddChunk (_stream_readable.js:237:11)
Command: E:\GitHub\node-chakracore3\Release\node.exe E:\GitHub\node-chakracore3\test\inspector\test-inspector-break-when-eval.js
```

When merging v8.1.0 there was also a new failure in `test-off-with-session-then-on`:
```
=== release test-off-with-session-then-on ===
Path: inspector/test-off-with-session-then-on
[err] Debugger listening on ws://127.0.0.1:9229/a10ce32e-bcf6-442d-af5e-77d68f0ef514
[err] For help see https://nodejs.org/en/docs/inspector
[err] 
[err] Debugger attached.
[err] Debugger listening on ws://127.0.0.1:9229/7aa7b82d-4d5c-481c-85d9-93092994fdd8
[err] For help see https://nodejs.org/en/docs/inspector
[err]
AssertionError [ERR_ASSERTION]: {"code":3221225477,"signal":null}
   at Anonymous function (E:\GitHub\node-chakracore\test\inspector\inspector-helper.js:486:9)
   at emitTwo (events.js:130:7)
   at emit (events.js:213:7)
   at _handle.onexit (internal/child_process.js:197:7)
Command: E:\GitHub\node-chakracore\Release\node.exe E:\GitHub\node-chakracore\test\inspector\test-off-with-session-then-on.js
```

**Comment by aschrijver** [comment]
I don't know if this is related but I have been stuck with both VS Code and Chrome debuggers due to this: https://github.com/nodejs/node/issues/7593

**Comment by kfarnung** [comment]
We'll track this work in #367.  It looks like the `test-off-with-session-then-on` test has been refactored out.
