### ISSUE TITLE
process.env.hasOwnProperty('abc') throws exception

### ISSUE THREAD

**Issue by jianchun** [nodejs/node-chakracore#36]
Node.js with v8 returns false but with chakracore throws.

```
node -pe "process.env.hasOwnProperty('abc')"
TypeError: Object expected
   at Global code ([eval]:1:1)
   at exports.runInThisContext (vm.js:54:3)
   at Anonymous function ([eval]-wrapper:6:1)
   at Module.prototype._compile (module.js:417:3)
   at Anonymous function (node.js:575:7)
   at _combinedTickCallback (node.js:399:9)
   at _tickCallback (node.js:430:11)
```

Found by #32.

**Comment by jianchun** [comment]
Found what's going on. Will fix and test related APIs thoroughly.
