### ISSUE TITLE
Inconsistent behaviour in 'Error.prepareStackTrace'

### ISSUE THREAD

**Issue by chopdown** [nodejs/node-chakracore#482]
* **Version**:
* **Platform**:
* **Subsystem**:

Version: v8.9.4
Platform: All
Subsystem: Error

node-source-map-support does not work on ChakraCore,  'Error.prepareStackTrace' is not same as nodejs. so we can't adds source map support for typescript stack traces.

**The test case:**

```
Error.prepareStackTrace = function () {
    return "hello Error.prepareStackTrace";
}
throw new Error();
```

**node-chakracore**

```
throw new Error();
^

Error
   at Anonymous function (F:\_\test.js:66:1)
   at Module.prototype._compile (module.js:643:5)
   at Module._extensions[.js] (module.js:654:3)
   at Module.prototype.load (module.js:556:3)
   at tryModuleLoad (module.js:499:5)
   at Module._load (module.js:491:3)
   at Module.runMain (module.js:684:3)
   at startup (bootstrap_node.js:188:9)
   at Anonymous function (bootstrap_node.js:612:3)
```

**node**

```
throw new Error();
^
hello Error.prepareStackTrace
```

**Comment by kfarnung** [comment]
Unfortunately `Error.prepareStackTrace` is not a standard API, so it's not surprising that it doesn't work the same way as V8:

https://github.com/v8/v8/wiki/Stack%20Trace%20API

> It is safe to set `Error.stackTraceLimit` and `Error.prepareStackTrace` regardless of which implementation is running your code but be aware that it will only have an effect if your code is running in V8.

It would be nice to have support for this, but for now we'll have to track it as a compatibility issue.  It's worth calling out that [node-source-map-support](https://github.com/evanw/node-source-map-support) states their usage of that specific V8 API for their implementation.
