### ISSUE TITLE
Failing test `parallel/test-async-hooks-destroy-on-gc`

### ISSUE THREAD

**Issue by kfarnung** [nodejs/node-chakracore#494]
* **Version**: master
* **Platform**: windows
* **Subsystem**: async-hooks

https://ci.nodejs.org/job/node-test-binary-windows/15609/COMPILED_BY=vs2017,RUNNER=win2008r2-vs2017,RUN_SUBSET=2/console

```
not ok 16 parallel/test-async-hooks-destroy-on-gc
  ---
  duration_ms: 0.253
  severity: fail
  stack: |-
    assert.js:253
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: false == true
       at Anonymous function (c:\workspace\node-test-binary-windows\test\parallel\test-async-hooks-destroy-on-gc.js:26:22)
       at runCallback (timers.js:696:5)
       at tryOnImmediate (timers.js:667:5)
       at processImmediate (timers.js:649:5)
  ...
```

**Comment by kfarnung** [comment]
This looks like it's probably flaky, maybe it's flaky upstream too?

EDIT: Probably not flaky upstream, likely to do with the different GC behavior of ChakraCore.

**Comment by kfarnung** [comment]
This looks to be a race condition.  On my machine it's basically 100% repro as part of the full test suite (with tests running in parallel), but 0% repro when run on its own.  If this hits in the next pump resolution I'll mark it flaky for now and investigate further.
