### ISSUE TITLE
Failling test `parallel/test-http2-respond-file-fd-invalid`

### ISSUE THREAD

**Issue by kfarnung** [nodejs/node-chakracore#495]
* **Version**: master
* **Platform**: linux
* **Subsystem**: http2

https://ci.nodejs.org/job/chakracore-test-linux/313/nodes=ubuntu1604-64/consoleText

```
not ok 929 parallel/test-http2-respond-file-fd-invalid
  ---
  duration_ms: 0.411
  severity: fail
  stack: |-
    (node:5343) ExperimentalWarning: The http2 module is an experimental API.
    assert.js:82
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: function should not have been called at /home/iojs/build/workspace/chakracore-test-linux/nodes/ubuntu1604-64/test/common/index.js:522
       at mustNotCall (/home/iojs/build/workspace/chakracore-test-linux/nodes/ubuntu1604-64/test/common/index.js:532:5)
       at Reflect.apply (native code:0:0)
       at emit (events.js:182:5)
       at addChunk (_stream_readable.js:271:5)
       at readableAddChunk (_stream_readable.js:256:11)
       at Readable.prototype.push (_stream_readable.js:212:3)
       at onStreamRead (internal/http2/core.js:378:5)
  ...
```

**Comment by kfarnung** [comment]
This looks like it's probably flaky, maybe it's flaky upstream too?
