### ISSUE TITLE
test-inspector-multisession unit tests failing

### ISSUE THREAD

**Issue by boingoing** [nodejs/node-chakracore#530]
* **Version**: Commit 1300103534
* **Platform**: Windows
* **Subsystem**: test

Two new unit tests test-inspector-multisession-js and test-inspector-multisession-ws are failing in node-chakracore. Looks like we are not receiving paused notifications in the debug session. Not sure why this is happening.

Here is the log output for these two tests:

```
not ok 1063 parallel/test-inspector-multisession-js
  ---
  duration_ms: 0.273
  severity: fail
  exitcode: 1
  stack: |-
    Connected
    Debugger was enabled
    Breakpoint was set
    e:\node\node-chakracore\test\common\index.js:873
                 (err) => process.nextTick(() => { throw err; }));
                                                   ^
    
    AssertionError [ERR_ASSERTION]: false == true
       at test (e:\node\node-chakracore\test\parallel\test-inspector-multisession-js.js:48:3)
       at Generator.prototype.next (native code:0:0)
       at _tickCallback (internal/process/next_tick.js:178:7)
       at Module.runMain (internal/modules/cjs/loader.js:721:3)
       at startup (internal/bootstrap/node.js:250:9)
       at bootstrapNodeJSCore (internal/bootstrap/node.js:601:3)
  ...
not ok 1064 parallel/test-inspector-multisession-ws
  ---
  duration_ms: 15.711
  severity: fail
  exitcode: 1
  stack: |-
    [test] Connecting to a child Node process
    [test] Testing /json/list
    [test] Connecting to a child Node process
    [test] Testing /json/list
    [err] Debugger listening on ws://127.0.0.1:10926/d0730fc9-5fb2-41b2-83cd-e05148be87c1
    [err] For help, see: https://nodejs.org/en/docs/inspector
    [err] 
    [test] Breaking in code and verifying events are fired
    [out] Ready
    [out] 
    Timed out waiting for matching notification (Console output))
    1
```

**Comment by boingoing** [comment]
These two tests are disabled via bf096ad69a
