### ISSUE TITLE
Test failures in `test-fs-stat-bigint` and `test-fs-watchfile-bigint` due to missing BigInt support

### ISSUE THREAD

**Issue by boingoing** [nodejs/node-chakracore#549]
* **Version**: master
* **Platform**: all
* **Subsystem**: fs

```
not ok 592 parallel/test-fs-stat-bigint
  ---
  duration_ms: 0.336
  severity: fail
  exitcode: 1
  stack: |-
    E:\node\node-chakracore\test\parallel\test-fs-stat-bigint.js:71
          assert(
          ^
    
    ReferenceError: 'BigInt' is not defined
       at verifyStats (E:\node\node-chakracore\test\parallel\test-fs-stat-bigint.js:69:7)
       at Anonymous function (E:\node\node-chakracore\test\parallel\test-fs-stat-bigint.js:82:3)
       at Module.prototype._compile (internal/modules/cjs/loader.js:702:5)
       at Module._extensions[.js] (internal/modules/cjs/loader.js:713:3)
       at Module.prototype.load (internal/modules/cjs/loader.js:612:3)
       at tryModuleLoad (internal/modules/cjs/loader.js:551:5)
       at Module._load (internal/modules/cjs/loader.js:543:3)
       at Module.runMain (internal/modules/cjs/loader.js:744:3)
       at startup (internal/bootstrap/node.js:267:9)
       at bootstrapNodeJSCore (internal/bootstrap/node.js:603:3)
...
not ok 615 parallel/test-fs-watchfile-bigint
  ---
  duration_ms: 0.282
  severity: fail
  exitcode: 1
  stack: |-
    E:\node\node-chakracore\test\parallel\test-fs-watchfile-bigint.js:12
      0n,                                        // dev
    ^
    
    SyntaxError: Unexpected identifier after numeric literal
       at Script (vm.js:80:7)
       at createScript (vm.js:234:3)
       at runInThisContext (vm.js:286:3)
       at Module.prototype._compile (internal/modules/cjs/loader.js:670:3)
       at Module._extensions[.js] (internal/modules/cjs/loader.js:713:3)
       at Module.prototype.load (internal/modules/cjs/loader.js:612:3)
       at tryModuleLoad (internal/modules/cjs/loader.js:551:5)
       at Module._load (internal/modules/cjs/loader.js:543:3)
       at Module.runMain (internal/modules/cjs/loader.js:744:3)
       at startup (internal/bootstrap/node.js:267:9)
```

Re-enable these tests when BigInt is implemented.

**Comment by joyeecheung** [comment]
Are there any plans in supporting BigInt in chakracore? I could not find any in https://github.com/Microsoft/ChakraCore

**Comment by boingoing** [comment]
It is on our radar though we haven't committed to a time frame that I know of, yet.
