### ISSUE TITLE
Flaky test `sequential/test-net-bytes-per-incoming-chunk-overhead`

### ISSUE THREAD

**Issue by kfarnung** [nodejs/node-chakracore#561]
* **Version**: master
* **Platform**: Windows
* **Subsystem**: net,test

It looks like `sequential/test-net-bytes-per-incoming-chunk-overhead` is flaky in the NodeJS Windows CI:

```
not ok 515 sequential/test-net-bytes-per-incoming-chunk-overhead
  ---
  duration_ms: 11.614
  severity: fail
  exitcode: 1
  stack: |-
    assert.js:273
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: measured 521.699328 bytes per chunk
       at Anonymous function (c:\workspace\node-test-binary-windows\test\sequential\test-net-bytes-per-incoming-chunk-overhead.js:40:3)
       at Reflect.apply (native code:0:0)
       at emit (events.js:187:7)
  …
```

I've seen this in master and v10.x only in the CI.

**Comment by addaleax** [comment]
You can bump the limit, it makes sense that it’s somewhat engine-specific. If ChakraCore’s ArrayBuffers and TypedArrays are larger than V8’s, then this is an expected result.

**Comment by kfarnung** [comment]
Ok, thanks!
