### ISSUE TITLE
Need support for the 3 dots operator to install tensorflow/tfjs-node

### ISSUE THREAD

**Issue by EricLi20** [nodejs/node-chakracore#620]
* **Version**: v10.13.0
* **Platform**:Windows 10.0.17763.316
* **Subsystem**:

Looks like ChakraCore might need to add support for the 3 dots operator (spread operator)?
Get the below error for both 10.13.0 & latest nightly.
Here's the file
https://github.com/tensorflow/tfjs-node/blob/master/scripts/install.js#L112

PS E:\tempBaseBall> nvs
PATH -= $env:LOCALAPPDATA\nvs\chakracore\10.13.0\x64
PATH += $env:LOCALAPPDATA\nvs\chakracore-nightly\12.0.0-nightly20190209744291b341\x64
PS E:\tempBaseBall> npm install @tensorflow/tfjs-node
npm WARN npm npm does not support Node.js v12.0.0-nightly20190209744291b341
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11.
npm WARN npm You can find the latest version at https://nodejs.org/

> @tensorflow/tfjs-node@0.2.3 install E:\tempBaseBall\node_modules\@tensorflow\tfjs-node
> node scripts/install.js

E:\tempBaseBall\node_modules\@tensorflow\tfjs-node\scripts\install.js:112
  const options = {...url.parse(targetUri), agent: https.globalAgent};
                            ^^^^

SyntaxError: Expected identifier, string or number
   at Script (vm.js:91:7)
   at createScript (vm.js:267:3)
   at runInThisContext (vm.js:319:3)
   at Module.prototype._compile (internal/modules/cjs/loader.js:685:3)
   at Module._extensions[.js] (internal/modules/cjs/loader.js:733:3)
   at Module.prototype.load (internal/modules/cjs/loader.js:620:3)
   at tryModuleLoad (internal/modules/cjs/loader.js:560:5)
   at Module._load (internal/modules/cjs/loader.js:552:3)
   at Module.runMain (internal/modules/cjs/loader.js:775:5)
   at startup (internal/bootstrap/node.js:301:9)
npm WARN tfjs-examples-baseball-node@0.2.0 No repository field.
npm WARN You are using a pre-release version of node and things may not work as expected
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tensorflow/tfjs-node@0.2.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tensorflow/tfjs-node@0.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Ahriana** [comment]
the spred operator is not supported in chakra IIRC, you would have to take it up with them

**Comment by rhuanjl** [comment]
If you build using chakracore master (use the branch chakracore-master from this repository)  and supply CC with the build flag ES2018ObjectRestSpread then this should be enabled - the support is experimental but I think it should work for 99% of use cases.
