### ISSUE TITLE
parseStack fails for certain Error messages

### ISSUE THREAD

**Issue by alexlamsl** [nodejs/node-chakracore#78]
- **Version**: v6.0.0-pre7
- **Platform**: Windows Server 2012r2

Logging `Error` messages can cause unexpected errors.

Reproduce using REPL - this works:

```
> new Error('\n\n\n')
Error:



   at Anonymous function (Unknown script code:238:20)
   at withStackTraceLimitOffset (Unknown script code:169:7)
   at __newType (Unknown script code:237:9)
   at Global code (repl:1:1)
   at defaultEval (repl.js:271:11)
   at bound (domain.js:280:5)
   at runBound (domain.js:293:5)
   at Anonymous function (repl.js:441:7)
   at emitOne (events.js:95:7)
   at emit (events.js:182:7)
   at Interface.prototype._onLine (readline.js:216:5)
   at Interface.prototype._line (readline.js:555:3)
   at Interface.prototype._ttyWrite (readline.js:832:9)
```

But this doesn't:

```
> new Error('\n\n\n\n')
TypeError: Unable to get property 'index' of undefined or null reference
   at parseStack (Unknown script code:98:7)
   at ensureStackTrace (Unknown script code:198:9)
   at stackGetter (Unknown script code:208:9)
   at formatError (util.js:525:3)
   at formatValue (util.js:310:7)
   at inspect (util.js:143:3)
   at self.writer (repl.js:365:7)
   at finish (repl.js:490:9)
   at defaultEval (repl.js:292:5)
   at bound (domain.js:280:5)
```

**Comment by alexlamsl** [comment]
Looks like the [magic number 3](https://github.com/nodejs/node-chakracore/blob/chakracore-master/deps/chakrashim/lib/chakra_shim.js#L176-179) didn't take possible `\n`s in `Error.message` into account...

**Comment by kunalspathak** [comment]
@alexlamsl - Thanks for reporting this. There are some other bugs in chakrashim and chakracore because of which `Error` is not behaving correctly. See #75 and Microsoft/chakracore#1128.

**Comment by alexlamsl** [comment]
@kunalspathak thanks for looking into this. I would just add that this bug is more severe than just giving the wrong stack trace - it is causing `console.log(err)` to terminate the whole Node.js process due to the new (unhandled) exception.
